[project]
name = "hyvor-smtp-bridge"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "aiosmtpd==1.4.6",
  "requests==2.32.3",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["smtp_bridge*"]
